#pragma once
#define Debug true
// Macros go here :)
#define FB_VERSION "v0.5"
#define FB_TARGET_TICKRATE 60
#define FB_TICKRATE_TIME (1000 / FB_TARGET_TICKRATE)
#define FB_DELTATIME (1.0 / FB_TARGET_TICKRATE)
#define FB_CONTAINER_OUTPUT 100
#define FB_CONTAINER_SIZE 0.03
#define FB_IMAGE_SCALE 5

#define FB_MOLECULE_COUNT 1
#define FB_MOLECULE_COL_BOUNDARY 1.000
#define FB_MOLECULE_SPAWNRANDOM true